# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

gimbal_position_controller:
    type: dji_m100_controllers/GimbalPositionController
    joints:
        - gimbal_roll_joint
        - gimbal_pitch_joint
        - gimbal_yaw_joint
    pid: {p: 100.0, i: 5, d: 7.0}